2024-10-27 11:19:17 - ERROR - done set
2024-10-27 11:21:01 - ERROR - done set
2024-10-27 11:23:51 - ERROR - This is an error message
2024-10-27 11:23:51 - CRITICAL - This is a critical message
2024-10-27 11:24:57 - ERROR - This is an error message
2024-10-27 11:24:57 - CRITICAL - This is a critical message
2024-10-28 17:39:27 - ERROR - [WinError 3] The system cannot find the path specified.
2024-10-28 17:42:11 - ERROR - [WinError 2] The system cannot find the file specified.
2024-10-28 17:57:27 - ERROR - Error cleaning up files: 'Orchestrator' object has no attribute 'db_strategy'
2024-10-29 12:05:34 - ERROR - Error cleaning up files: 'kwargs'
2024-10-29 12:05:34 - ERROR - Error cleaning up files: 'kwargs'
2024-10-29 12:05:34 - ERROR - Error cleaning up files: 'kwargs'
2024-10-29 12:05:34 - ERROR - Error cleaning up files: 'kwargs'
2024-10-29 12:05:34 - ERROR - Error cleaning up files: 'kwargs'
2024-10-29 12:05:34 - ERROR - Error cleaning up files: 'kwargs'
2024-10-29 12:05:34 - ERROR - Error cleaning up files: 'kwargs'
2024-10-29 12:05:34 - ERROR - Error cleaning up files: 'kwargs'
2024-10-29 12:05:34 - ERROR - Error cleaning up files: 'kwargs'
2024-10-29 12:05:34 - ERROR - Error cleaning up files: 'kwargs'
2024-10-29 16:39:21 - ERROR - Error during request: HTTPConnectionPool(host='0.0.0.0', port=8000): Max retries exceeded with url: /merge-files/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0438A538>: Failed to establish a new connection: [WinError 10049] The requested address is not valid in its context'))
2024-10-29 16:39:22 - ERROR - Error during request: HTTPConnectionPool(host='0.0.0.0', port=8000): Max retries exceeded with url: /merge-files/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0438AA48>: Failed to establish a new connection: [WinError 10049] The requested address is not valid in its context'))
2024-10-29 17:32:32 - ERROR - Error during request: Expecting value: line 1 column 1 (char 0)
2024-10-29 17:32:33 - ERROR - Error during request: Expecting value: line 1 column 1 (char 0)
2024-10-29 17:33:34 - ERROR - Error during request: Expecting value: line 1 column 1 (char 0)
2024-10-29 17:33:35 - ERROR - Error during request: Expecting value: line 1 column 1 (char 0)
2024-10-29 23:44:50 - ERROR - Error during request: HTTPConnectionPool(host='172.17.64.1', port=8000): Max retries exceeded with url: /merge-files/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x045EB520>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2024-10-29 23:44:51 - ERROR - Error during request: HTTPConnectionPool(host='172.17.64.1', port=8000): Max retries exceeded with url: /merge-files/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x045EBD00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2024-10-29 23:47:11 - ERROR - Error during request: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2024-10-29 23:47:11 - ERROR - Error during request: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2024-10-29 23:47:11 - ERROR - Error during request: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2024-10-29 23:47:11 - ERROR - Error during request: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2024-10-30 10:07:41 - ERROR - Error during request: HTTPConnectionPool(host='172.17.64.1', port=8000): Max retries exceeded with url: /merge-files/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x074D2538>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2024-10-30 10:07:43 - ERROR - Error during request: HTTPConnectionPool(host='172.17.64.1', port=8000): Max retries exceeded with url: /merge-files/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0771BE68>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2024-10-30 10:14:10 - ERROR - Error during request: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2024-10-30 10:14:10 - ERROR - Error during request: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2024-10-30 10:14:10 - ERROR - Error during request: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2024-10-30 13:17:36 - ERROR - Error during request: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2024-10-30 13:17:36 - ERROR - Error during request: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2024-10-30 13:18:45 - ERROR - Error during request: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2024-10-30 13:18:45 - ERROR - Error during request: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2024-10-30 13:24:18 - ERROR - Error during request: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2024-10-30 13:24:18 - ERROR - Error during request: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2024-10-30 13:26:59 - ERROR - Error during request: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2024-10-30 13:26:59 - ERROR - Error during request: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2024-10-30 13:36:45 - ERROR - Error during request: HTTPConnectionPool(host='172.17.64.1', port=8000): Max retries exceeded with url: /merge-files/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x07393340>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2024-10-30 13:36:45 - ERROR - Error during request: HTTPConnectionPool(host='172.17.64.1', port=8000): Max retries exceeded with url: /merge-files/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x073931F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2024-10-30 14:37:54 - ERROR - Error during request: HTTPConnectionPool(host='172.17.64.1', port=8000): Max retries exceeded with url: /merge-files/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04983748>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2024-10-30 19:29:43 - ERROR - Error during request: HTTPConnectionPool(host='0.0.0.0', port=8000): Max retries exceeded with url: /merge-files/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x043BC4D8>: Failed to establish a new connection: [WinError 10049] The requested address is not valid in its context'))
2024-10-30 19:29:44 - ERROR - Error during request: HTTPConnectionPool(host='0.0.0.0', port=8000): Max retries exceeded with url: /merge-files/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x043BC9D0>: Failed to establish a new connection: [WinError 10049] The requested address is not valid in its context'))
2024-10-30 19:29:45 - ERROR - Error during request: HTTPConnectionPool(host='0.0.0.0', port=8000): Max retries exceeded with url: /merge-files/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04842028>: Failed to establish a new connection: [WinError 10049] The requested address is not valid in its context'))
2024-10-30 19:29:46 - ERROR - Error during request: HTTPConnectionPool(host='0.0.0.0', port=8000): Max retries exceeded with url: /merge-files/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x043BCDC0>: Failed to establish a new connection: [WinError 10049] The requested address is not valid in its context'))
2024-10-30 19:29:48 - ERROR - Error during request: HTTPConnectionPool(host='0.0.0.0', port=8000): Max retries exceeded with url: /merge-files/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04842220>: Failed to establish a new connection: [WinError 10049] The requested address is not valid in its context'))
2024-10-30 19:29:49 - ERROR - Error during request: HTTPConnectionPool(host='0.0.0.0', port=8000): Max retries exceeded with url: /merge-files/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04842838>: Failed to establish a new connection: [WinError 10049] The requested address is not valid in its context'))
2024-10-30 19:29:50 - ERROR - Error during request: HTTPConnectionPool(host='0.0.0.0', port=8000): Max retries exceeded with url: /merge-files/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04842E08>: Failed to establish a new connection: [WinError 10049] The requested address is not valid in its context'))
2024-10-30 19:29:51 - ERROR - Error during request: HTTPConnectionPool(host='0.0.0.0', port=8000): Max retries exceeded with url: /merge-files/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04842E68>: Failed to establish a new connection: [WinError 10049] The requested address is not valid in its context'))
2024-10-30 19:29:52 - ERROR - Error during request: HTTPConnectionPool(host='0.0.0.0', port=8000): Max retries exceeded with url: /merge-files/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04842A90>: Failed to establish a new connection: [WinError 10049] The requested address is not valid in its context'))
2024-10-31 11:20:44 - ERROR - Error during request: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2024-10-31 11:20:44 - ERROR - Error during request: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
